workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web App
        script: |
          npm run build:js
      - name: Capacitor Sync
        script: |
          npx cap sync ios
      - name: Test iOS Build (Without Code Signing)
        script: |
          cd ios/App
          xcodebuild build -project App.xcodeproj -scheme App -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO