workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mohamedashraf.aqra

      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: |
          -----BEGIN PRIVATE KEY-----
          YOUR_KEY
          -----END PRIVATE KEY-----
        key_id: 2WZZPVD7N2
        issuer_id: 31c5c3e7-22bb-499b-8d0f-df7e49582ae1

        submit_to_testflight: true
        submit_to_app_store: false
